#!/bin/sh

# make this file executable and add to path
# export PATH="$HOME/.dotfiles/git/:$PATH"

((!$#)) && echo No remote name, command ignored! && exit 1
URL=`git config --get remote.$1.url`
git remote remove $1
git remote add $1 $URL
echo Cleaned remote $1
